config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#top'

  get :sign_up, to: 'users#new'
  get :login, to: 'sessions#new'
  post :login, to: 'sessions#create'
  delete :logout, to: 'sessions#destroy'

  resources :spaces do
    collection do
      get :search
    end
    member do
      get :reservations
    end
    member do
      post :toggle_visible
    end
  end
  resources :users, except: [:index] do
    member do
      get :spaces
      get :reservations
    end
  end
  resources :reservations, only: [:new, :create, :show, :destroy]
  resources :owners, only: [:index]
  resources :clients, only: [:index]

  namespace :admin do
    get :top, to: 'pages#top'
    resources :users, only: [:index, :update, :destroy]
    resources :spaces, only: [:index, :update, :destroy] do
      member do
        post :authorize
        post :drop
      end
    end
    resources :reservations, only: [:index, :update, :destroy]
  end
end

app/models/space.rb
class Space < ActiveRecord::Base

  has_many :options, inverse_of: :space, dependent: :destroy
  accepts_nested_attributes_for :options, allow_destroy: true
  has_many :reservations, dependent: :destroy
  belongs_to :user

  scope :visible, -> { where(visible: true) }
  scope :recent, -> { order(created_at: :desc) }

  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment :photo, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

  validates :name, presence: true
  validates :address, presence: true
  # validates :tel, presence: true
  validates :member_limit, presence: true
  validates :charge, presence: true
  # validates :min_time_block
  # validates :max_time_block
  # validates :start_time_block
  # validates :finish_time_block
  validates :description, presence: true
  validates :cancellation_charge, presence: true
  validates :space_type, presence: true
  # validates :owner_id
  # validates :visible
  # validates :autherized

  def available_list_at(date)
    reservations = Reservation.where(date: date.beginning_of_day..date.end_of_day, space_id: self)
    list = 48.times.map{ true }
    reservations.each{ |r| list.fill(false, r.start_time_block..r.end_time_block) }
    list
  end


  def space_type_text
    case self.space_type
      when 0
        '会議室'
      when 1
        'スタジオ'
      when 2
        'ホール'
      elsere
        '未分類'
    end
  end
end

app/controllers/admin/spaces_controller.rb
class Admin::SpacesController < ApplicationController
  before_action :set_space, only: [:authorize, :drop]

  def index
    @spaces = Space.all
  end

  def update
  end

  def authorize
    flash[:success] = '認可しました。'
    @space.update(authorized: true)
    redirect_to admin_spaces_path
  end

  def drop
    flash[:success] = '強制非公開にしました。'
    @space.update(visible: false)
    redirect_to admin_spaces_path
  end

  private
  def set_space
    @space = Space.find(params[:id])
  end
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  before_action :set_space, only:[:show, :edit, :update, :destroy, :toggle_visible, :reservations]
  def index
    @spaces = Space.recent.visible.where(authorized: true)
    unless params[:q].blank?
      @spaces = @spaces.where('name like ? or description like ? or address like ?', "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%")
    end
    unless params[:num].blank?
      @spaces = @spaces.where("member_limit #{params[:cond] == 'gt' ? '>' : '<'} ?", params[:num])
    end
  end

  def show
    @available_list = []
    7.times do |day|
      @available_list << @space.available_list_at(Time.now + day.day)
    end
  end

  def new
    @space = Space.new
    @user = current_user
  end

  def create
    @space = Space.new(space_params)
    if @space.save
      flash[:success] = 'スペースの登録に成功しました'
      redirect_to @space
    else
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @space.destroy
    flash[:success] = 'スペースを削除しました'
    redirect_to root_path
  end

  def toggle_visible
    @space.update(visible: false)
    redirect_to @space
  end

  def reservations
    @reservations = @space.reservations
  end

  private
  def space_params
    params.require(:space).permit(
                              :user_id,
                              :name,
                              :address,
                              :mail_address,
                              :tel,
                              :description,
                              :photo,
                              :charge,
                              :cancellation_charge,
                              :member_limit,
                              :space_type,
                              options_attributes: [:space_id, :option_name, :count, :charge, :_destroy]
    )
  end

  def set_space
    @space = Space.find(params[:id])
  end
end

app/views/spaces/_option.html.erb
<tr>
  <td><%= option.option_name %></td>
  <td><%= option.charge %>円</td>
  <td><%= option.count %></td>
</tr>

app/views/spaces/_search.html.erb
<div class="panel panel-info">
  <div class="panel-heading">絞り込み検索</div>
  <div class="panel-body">
    <%= form_tag spaces_path, method: :get do %>
        <%= label_tag '検索ワード' %>
        <%= text_field_tag :q %>
        <br>
        <%= label_tag '人数' %>
        <%= number_field_tag :num %>
        <%= select_tag :cond, options_for_select([%w(以上 gt), %w(以下 ls)]) %>

        <%= submit_tag  '検索', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/spaces/index.html.erb
<h1>スペースの一覧</h1>
<%= render 'spaces/search' %>
<% @spaces.each do |space| %>
    <%= render 'shared/space_index', space: space %>
<% end %>

app/views/spaces/new.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>スペース新規登録</h1>
    <%= nested_form_for @space do |f| %>
        <%= render 'shared/error_message', target: @space %>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <div class="row">
          <div class="col-md-5">
            <%= f.label 'スペースの名前' %>
            <%= f.text_field :name, class: 'form-control' %>
            <br>
            <%= f.label '住所' %>
            <%= f.text_field :address, class: 'form-control' %>
          </div>
          <div class="col-md-7">
            <%= f.label 'スペースの説明' %>
            <%= f.text_area :description, size: '20x5', class: 'form-control' %>
          </div>
        </div>
        <br>

        <div class="row">
          <div class="col-md-3">
            <%= f.label '連絡先(電話)' %>
            <%= f.text_field :tel, class: 'form-control' %>
          </div>
          <div class="col-md-3">
            <%= f.label '連絡先(メール)' %>
            <%= f.text_field :mail_address, class: 'form-control' %>
          </div>
          <div class="col-md-6">
            <div class="field">
              <%= f.label '添付画像' %>
              <%= f.file_field :photo, class: 'form-control' %>
            </div>
          </div>
        </div>
        <br>
        <div class="row">
          <div class="col-md-3">
            <%= f.label '値段(30分あたり)' %>
            <%= f.number_field :charge, class: 'form-control' %>
          </div>
          <div class="col-md-3">
            <%= f.label 'キャンセル料金' %>
            <%= f.number_field :cancellation_charge, class: 'form-control' %>
          </div>
          <div class="col-md-3">
            <%= f.label '最大収容人数' %>
            <%= f.number_field :member_limit, class: 'form-control' %>
          </div>
          <div class="col-md-3">
            <%= f.label 'タイプ' %>
            <%= f.select :space_type, [['会議室', 0], ['スタジオ', 1], ['ホール', 2]], {}, class: 'form-control'  %>
          </div>
        </div>
        <br>
        <% f.fields_for :options do |option| %>
          <div class="panel panel-default">
            <div class="panel-body">
              <div class="row">
                <div class="col-md-12">
                  <div class="row">
                    <div class="col-md-6">
                      <%= option.label '備品名' %>
                      <%= option.text_field :option_name, class: 'form-control' %>
                    </div>
                    <div class="col-md-3">
                      <%= option.label '値段(30分あたり)' %>
                      <%= option.number_field :charge, class: 'form-control' %>
                    </div>
                    <div class="col-md-3">
                      <%= option.label '個数' %>
                      <%= option.number_field :count, class: 'form-control' %>
                    </div>
                  </div>
                  <%= option.hidden_field :space_id, value: @space.id %>
                  <br>
                  <%= option.link_to_remove '備品の削除', class: 'btn btn-warning' %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
        <%= f.link_to_add '備品を追加する', :options, class: 'btn btn-default' %>
        <br>
        <br>
        <%= f.submit '登録', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/spaces/reservations.html.erb
<h3>スペースについた予約一覧</h3>
<p>スペースについた予約を見ることが出来ます。</p>
<%= link_to 'スペースの削除', space_path(@space), class: 'btn btn-danger', method: :delete %>
<%= render 'shared/space_index', space: @space %>
<% @reservations.each do |reservation| %>
    <div class="column">
      <div class="col-md-2">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">操作</h3>
          </div>
          <div class="panel-body text-center">
            <%= link_to '予約削除', reservation_path(reservation, force: true), class: 'btn btn-primary navbar-btn', method: :delete %>
          </div>
        </div>
      </div>
      <div class="col-md-10">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title"><%= reservation.user.name %>さんの予約</h3>
          </div>
          <div class="panel-body">
            <div class="media">
              <div class="media-body">
                <table class="table">
                  <tr>
                    <th>合計金額</th>
                    <th>開始枠</th>
                    <th>終了枠</th>
                    <th>オプション</th>
                  </tr>
                  <tr>
                    <td><%= reservation.total_charge %>円</td>
                    <td><%= Reservation.time_block_text(reservation.start_time_block) %></td>
                    <td><%= Reservation.time_block_text(reservation.end_time_block) %></td>
                    <td><%= reservation.options.exists? ? 'あり' : 'なし' %></td>
                  </tr>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/spaces/show.html.erb
<div class="row">
  <div class="col-md-4">
    <% if @space.photo.present? %>
        <%= image_tag @space.photo.url(:midium) %>
    <% else %>
        <%= image_tag 'missing_photo.png' %>
    <% end %>
  </div>
  <div class="col-md-8">
    <h1><%= @space.name %></h1>
    <p><%= @space.description %></p>
    <table class="table">
      <tr>
        <th>値段(/30min)</th>
        <th>人数制限</th>
        <th>タイプ</th>
        <th>住所</th>
      </tr>
      <tr>
        <td><%= @space.charge %>円</td>
        <td><%= @space.member_limit %></td>
        <td><%= @space.space_type_text %></td>
        <td><%= @space.address %></td>
      </tr>
      <tr>
        <th>キャンセル料</th>
        <th>連絡先</th>
        <th>登録者</th>
        <th></th>
      </tr>
      <tr>
        <td><%= @space.cancellation_charge %>円</td>
        <td><%= @space.tel.present? ? @space.tel : @space.mail_address %></td>
        <td><%= @space.user.name %></td>
        <td></td>
      </tr>
    </table>
  </div>
</div>
<br>
<% unless @space.options.blank? %>
    <div class="panel panel-default">
      <div class="panel-body">
        <table class="table">
          <tr>
            <th>備品名</th>
            <th>値段(/30min)</th>
            <th>個数</th>
          </tr>
          <% @space.options.each do |option| %>
              <%= render 'spaces/option', option: option %>
          <% end %>
        </table>
      </div>
    </div>
<% end %>

<h4>スペース使用状況</h4>
<p>「○」になっている所をクリックすることで、予約が行えます。</p>
<div class="row">
  <table class="table">
    <tr>
      <th class="text-center">時間</th>
      <% 7.times do |day| %>
          <th class="text-center"><%= (Time.now + day.day).strftime('%m/%d') %></th>
      <% end %>
    </tr>
    <% 48.times do |time| %>
        <tr>
          <th><%= Reservation.time_block_text(time) %>~</th>
          <% 7.times do |day| %>
            <td class="text-center"><%= @available_list[day][time] ? current_user.try(:client?) ? link_to('○' , new_reservation_path(space: @space.id, start: time, date: Time.now + day.day)) : '○' : '×' %></td>
          <% end %>
        </tr>
    <% end %>
  </table>

</div>