config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#top'

  get :sign_up, to: 'users#new'
  get :login, to: 'sessions#new'
  post :login, to: 'sessions#create'
  delete :logout, to: 'sessions#destroy'

  resources :spaces do
    collection do
      get :search
    end
    member do
      get :reservations
    end
    member do
      post :toggle_visible
    end
  end
  resources :users, except: [:index] do
    member do
      get :spaces
      get :reservations
    end
  end
  resources :reservations, only: [:new, :create, :show, :destroy]
  resources :owners, only: [:index]
  resources :clients, only: [:index]

  namespace :admin do
    get :top, to: 'pages#top'
    resources :users, only: [:index, :update, :destroy]
    resources :spaces, only: [:index, :update, :destroy] do
      member do
        post :authorize
        post :drop
      end
    end
    resources :reservations, only: [:index, :update, :destroy]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  enum member_type: { client: 0, owner: 1}

  has_many :reservations, dependent: :destroy
  has_many :spaces, dependent: :destroy

  validates :mail, uniqueness: true, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :name, presence: true,
            length: { in: 3..15 }
  validates :password, presence: { on: :create },
            confirmation: { allow_blank: true },
            length: { in: 4..12 }


end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all
  end

  def update
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :spaces, :reservations]
  before_action :owner_only, only: [:owners]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = 'ユーザー登録に成功しました'
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = '情報を変更しました！'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    if @user.reservations.exists?
      flash[:danger] = '予約が残っています。全てキャンセルしてから退会して下さい。'
      render 'edit'
    elsif @user.spaces.exists?
      flash[:danger] = 'スペースが残っています。全てのスペースを削除してから退会して下さい。'
      render 'edit'
    else
      log_out
      @user.destroy
      flash[:success] = '退会に成功しました'
      redirect_to root_url
    end
  end

  def spaces
    @spaces = Space.recent.where(user_id: params[:id])
  end

  def reservations
    @reservations = Reservation.recent.where(user_id: params[:id])
  end

  private
  def user_params
    params.require(:user).permit(
                             :mail,
                             :name,
                             :password,
                             :member_type
    )
  end

  def set_user
    @user = User.find(params[:id])
  end

  def owner_only
    unless User.find(params[:id]).owner?
      flash[:error] = 'オーナー専用です'
      redirect_to user_path User.find(params[:id])
    end
  end
end

app/views/users/_header.html.erb
<h1><%= user.name %>さんのマイページ</h1>
<ul class="nav nav-tabs" role="tablist">
  <li role="presentation"><%= link_to 'プロフィール', user_path(user) %></li>
  <% if user.owner? %>
    <li role="presentation"><%= link_to '登録したスペース', spaces_user_path(user) %></li>
  <% end %>
  <% if params[:id].to_i == current_user.id %>
      <% if user.owner? %>
        <li role="presentation"><%= link_to 'スペースの新規登録', new_space_path %></li>
      <% end %>
      <% if user.client? %>
        <li role="presentation"><%= link_to '予約の確認', reservations_user_path(user) %></li>
      <% end %>
      <li role="presentation"><%= link_to 'ID情報変更', edit_user_path(user) %></li>
  <% end %>
</ul>

app/views/users/edit.html.erb
<%= render 'users/header', user: @user  %>
<div class="tab-content">
  <div class="tab-pane active">
    <h3>アカウント情報変更</h3>
    <%= form_for @user do |f| %>
        <%= render 'shared/error_message',target: @user %>
        <%= f.label '表示名' %>
        <%= f.text_field :name, class: 'form-control' %>
        <br>
        <%= f.label 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
        <br>
        <%= f.submit '情報更新', class: 'btn btn-primary' %>
    <% end %>
    <p><%= link_to 'アカウントを削除する', user_path, confirm: '本当に削除しますか？', method: :delete %></p>
  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>ユーザー登録</h1>
    <%= form_for @user do |f| %>
        <%= render 'shared/error_message',target: @user %>
        <%= f.label 'メールアドレス' %>
        <%= f.email_field :mail, class: 'form-control' %>
        <br>
        <%= f.label '表示名' %>
        <%= f.text_field :name, class: 'form-control' %>
        <br>
        <%= f.label 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
        <br>
        <%= f.label '登録種別' %>
        <%= f.select :member_type, { '借り手': :client, '貸し手': :owner}, {}, class: 'form-control' %>
        <br>
        <%= f.submit 'ユーザー登録', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/users/reservations.html.erb
<%= render 'users/header', user: @user %>
<div class="tab-content">
  <div class="tab-pane active">
    <h3>あなたの予約一覧</h3>
    <% @reservations.each do |reservation| %>
        <div class="column">
          <div class="col-md-2">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title">操作</h3>
              </div>
              <div class="panel-body text-center">
                <%= link_to '予約取り消し', reservation_path(reservation), class: 'btn btn-primary navbar-btn', method: :delete %>
              </div>
            </div>
          </div>
          <div class="col-md-10">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title"><%= reservation.space.name %>(<%= reservation.date %>) </h3>
              </div>
              <div class="panel-body">
                <div class="media">
                  <div class="media-left">
                    <a href="#">
                      <% if reservation.space.photo.present? %>
                          <%= image_tag reservation.space.photo.url(:thumb), width: '150px' %>
                      <% else %>
                          <%= image_tag 'missing_thumb.png' %>
                      <% end %>
                    </a>
                    <div class="text-center">
                      <%= link_to space_path reservation.space do %>
                          <button type="button" class="btn btn-primary navbar-btn">詳細を見る</button>
                      <% end %>
                    </div>
                  </div>
                  <div class="media-body">
                    <p><%= reservation.space.description %></p>
                    <table class="table">
                      <tr>
                        <th>値段(/30min)</th>
                        <th>人数制限</th>
                        <th>タイプ</th>
                        <th>住所</th>
                      </tr>
                      <tr>
                        <td><%= reservation.space.charge %>円</td>
                        <td><%= reservation.space.member_limit %></td>
                        <td><%= reservation.space.space_type_text %></td>
                        <td><%= reservation.space.address %></td>
                      </tr>
                      <tr>
                        <th>合計金額</th>
                        <th>開始枠</th>
                        <th>終了枠</th>
                        <th>オプション</th>
                      </tr>
                      <tr>
                        <td><%= reservation.total_charge %>円</td>
                        <td><%= Reservation.time_block_text(reservation.start_time_block) %></td>
                        <td><%= Reservation.time_block_text(reservation.end_time_block) %></td>
                        <td><%= reservation.options.exists? ? 'あり' : 'なし' %></td>
                      </tr>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= render 'users/header', user: @user, params: params %>
<div class="tab-content">
  <div class="tab-pane active">
    <h3>あなたのアカウント情報</h3>
    <table class="table table-bordered table-hover">
      <tr>
        <th>メールアドレス</th>
        <td><%= @user.mail %></td>
      </tr>
      <tr>
        <th>名前</th>
        <td><%= @user.name %></td>
      </tr>
      <tr>
        <th>アカウントタイプ</th>
        <td><%= @user.member_type %></td>
      </tr>
    </table>
  </div>
</div>

app/views/users/spaces.html.erb
<%= render 'users/header', user: @user %>
<div class="tab-content">
  <div class="tab-pane active">
    <h3>あなたの登録しているスペース</h3>
    <% @spaces.each do |space| %>
        <div class="column">
          <div class="col-md-2">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title">操作</h3>
              </div>
              <div class="panel-body text-center">
                <%= link_to '公開設定変更', toggle_visible_space_path(space), class: 'btn btn-primary navbar-btn', method: :post %>
                <p>現在 <%= space.visible? ? '公開中' : '非公開' %></p>
                <%= link_to '予約一覧', reservations_space_path(space), class: 'btn btn-primary navbar-btn' %>
              </div>
            </div>
          </div>
          <div class="col-md-10">
            <%= render 'shared/space_index', space: space %>
          </div>
        </div>
    <% end %>
  </div>
</div>