config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#top'

  get :sign_up, to: 'users#new'
  get :login, to: 'sessions#new'
  post :login, to: 'sessions#create'
  delete :logout, to: 'sessions#destroy'

  resources :spaces do
    collection do
      get :search
    end
    member do
      get :reservations
    end
    member do
      post :toggle_visible
    end
  end
  resources :users, except: [:index] do
    member do
      get :spaces
      get :reservations
    end
  end
  resources :reservations, only: [:new, :create, :show, :destroy]
  resources :owners, only: [:index]
  resources :clients, only: [:index]

  namespace :admin do
    get :top, to: 'pages#top'
    resources :users, only: [:index, :update, :destroy]
    resources :spaces, only: [:index, :update, :destroy] do
      member do
        post :authorize
        post :drop
      end
    end
    resources :reservations, only: [:index, :update, :destroy]
  end
end

app/views/shared/_error_message.html.erb
<% if target.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(target.errors.count, "error") %>.
      </div>
      <ul>
        <% target.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_nav_bar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="<%= root_path %>">インスペ</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'スペース一覧', spaces_path %></li>
        <li><a href="#">利用規約</a></li>
        <% if logged_in? %>
            <p class="navbar-text">ようこそ <%= current_user.name %>さん</p>
            <% if current_user.admin? %>
              <%= link_to admin_top_path do %>
                <button type="button" class="btn btn-primary navbar-btn">管理者画面</button>
              <% end %>
            <% else %>
              <%= link_to user_path current_user do %>
                <button type="button" class="btn btn-default navbar-btn">マイページ</button>
              <% end %>
            <% end %>
        <% else %>
            <%= link_to login_path do %>
                <button type="button" class="btn btn-default navbar-btn">LogIn</button>
            <% end %>
            <%= link_to sign_up_path do %>
                <button type="button" class="btn btn-primary navbar-btn">Sign Up</button>
            <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_space_index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= space.name %></h3>
  </div>
  <div class="panel-body">
    <div class="media">
      <div class="media-left">
        <a href="#">
          <% if space.photo.present? %>
            <%= image_tag space.photo.url(:thumb), width: '150px' %>
          <% else %>
            <%= image_tag 'missing_thumb.png' %>
          <% end %>
        </a>
        <div class="text-center">
          <%= link_to space_path space do %>
            <button type="button" class="btn btn-primary navbar-btn">詳細を見る</button>
          <% end %>
        </div>
      </div>
      <div class="media-body">
        <p><%= space.description %></p>
        <table class="table">
          <tr>
            <th>値段(/30min)</th>
            <th>人数制限</th>
            <th>タイプ</th>
            <th>住所</th>
          </tr>
          <tr>
            <td><%= space.charge %></td>
            <td><%= space.member_limit %></td>
            <td><%= space.space_type_text %></td>
            <td><%= space.address %></td>
          </tr>
        </table>
      </div>
    </div>
  </div>
</div>